### ISSUE TITLE
Extra `foo()` Test Being Displayed

### ISSUE THREAD

**Issue by bakejeyner** [kotlintest/kotlintest#317] opened 2018-05-02 22:17 UTC
When running `kotlintest` unit tests, an extra `foo()` test is being displayed as passing.

Probable cause: https://github.com/kotlintest/kotlintest/blob/master/kotlintest-runner/kotlintest-runner-junit5/src/main/kotlin/io/kotlintest/specs/specs.kt#L8-L10

I am writing tests for a gradle project. Here are the versions.
`kotlintest` version: `3.1.0-RC2`
`kotlin` version: `1.2.41`
`gradle` version: `4.7`

Screenshot of the extra `foo()` test in Intellij.
![image](https://user-images.githubusercontent.com/14284361/39551556-53d5c096-4e1a-11e8-9bcb-1524276ef07d.png)

**Comment by sksamuel** [comment] 2018-05-02 22:36
The foo() dummy test is definitely the cause, but this would only happen if you had junit-jupiter on the classpath, which isn't pulled in by kotlintest by default.

The reason for the dummy test is in order to fool intellij into putting the little green arrow next to the test class.

**Comment by coyotesqrl** [comment] 2018-05-03 12:53
In a mixed language environment with a combination of JUnit 5 and kotlintest tests, I think that would happen pretty commonly. I'm curious if there might be another way to fool IJ instead of battling with the classpath.

**Comment by sksamuel** [comment] 2018-05-03 13:27
It is usual to have junit tests and kotlintest tests in the same project?

I would like to find another way to fool intellij though. Let me have a think and a play. I'm pretty close with an intellij plugin anyway, which would be the best solution - the intellij plugin is the main focus of 3.2

**Comment by coyotesqrl** [comment] 2018-05-03 13:32
We're experiencing that now, where older Java code with extant JUnit tests is living side-by-side with newer Kotlin code and kotlintest. The dummy test reporting isn't the biggest deal in the world, but it is a bit of noise we'd be happier to get rid of.

I'm definitely excited about the progress on the IJ plugin and look forward to it. We're loving kotlintest.

**Comment by sksamuel** [comment] 2018-05-03 13:43
thanks for the feedback :)

**Comment by sksamuel** [comment] 2018-05-07 21:06
I've made a change that should yield better results. If you want to try it, please try with 3.1.0-RC3.

**Comment by sksamuel** [comment] 2018-05-08 17:47
The RC3 doesn't look like it made any differnce now I tested it more, but I believe I do have a working fix in master currently ready for RC4 or 3.1.0 final. @bakejeyner  @coyotesqrl

**Comment by sksamuel** [comment] 2018-05-10 14:11
Ok 3.1.0-RC4 is now released and I think you should be good. Let me know and we can close this ticket.

**Comment by bakejeyner** [comment] 2018-05-10 23:03
👍 The extra `foo()` is gone, works like a charm! Thanks!

**Comment by coyotesqrl** [comment] 2018-05-11 00:33
Thanks, Stephen!

**Comment by sksamuel** [comment] 2018-05-11 12:54
3.1.0 final is now released. Closing ticket.

**Closed by sksamuel** 2018-05-11 12:54 UTC
Labels: bug, enhancement
