### ISSUE TITLE
Reflection error

### ISSUE THREAD

**Issue by AleksandrSl** [kotlintest/kotlintest#244] opened 2017-12-21 10:59 UTC
With `kotlin 1.2.10` and `kotlintest >= 2.0.6` I get following error:
```
java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;

	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at io.kotlintest.Project.<init>(Project.kt:17)
	at io.kotlintest.Project.<clinit>(Project.kt:8)
	at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Code for the test class:
```
import io.kotlintest.matchers.shouldBe
import io.kotlintest.specs.ShouldSpec


class Test : ShouldSpec(){

    init {
        should("should parse cwl doc") {
            1 shouldBe 1
        }
    }
}
```

**Comment by ddmytrenko** [comment] 2018-01-31 15:07
@AleksandrSl Are you using this with Android?

**Comment by AleksandrSl** [comment] 2018-01-31 15:22
@ddmytrenko No, for backend development

**Comment by stalexxx** [comment] 2018-02-23 11:31
I got something  like that:
Feb 23, 2018 2:28:24 PM org.reflections.ReflectionUtils forName
WARNING: could not get type for name com.sun.applet2.preloader.event.PreloaderEvent from any class loader
org.reflections.ReflectionsException: could not get type for name com.sun.applet2.preloader.event.PreloaderEvent
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at org.reflections.Reflections.<init>(Reflections.java:168)
        at io.kotlintest.Project.discoverProjectConfig(Project.kt:15)
        at io.kotlintest.Project.<init>(Project.kt:27)
        at io.kotlintest.Project.<clinit>(Project.kt:8)
        at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: com.sun.applet2.preloader.event.PreloaderEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 29 more

by the way, class is different every time. Start after I added another dependecy, don't have any conflicts in tree, kotlin 1.2.21

Another question - why using such a heavy location mechanism(reflections), time lag is annoying

**Comment by sksamuel** [comment] 2018-03-20 01:55
Fixed in 3.0.0.

**Closed by sksamuel** 2018-03-20 01:55 UTC
Labels: bug

**Comment by AleksandrSl** [comment] 2018-03-20 04:32
Thanks!

**Comment by zakyvr** [comment] 2018-03-28 16:08
Is there any workaround until 3.0.0 is released?

**Comment by sksamuel** [comment] 2018-03-28 16:12
No unfortunately, but 3.0.0 is a day away. If I don't see any complaints about RC4 I'll release that as 3.0.0. I can always turn around bugs in 3.0.1
