### ISSUE TITLE
Clarify on the use of useJUnitPlatform()

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#279] opened 2018-04-11 13:59 UTC
The changelog [states](https://github.com/kotlintest/kotlintest/blame/master/CHANGELOG.md#L367-L368) that even with Gradle 4.6 applying the JUnit Platform plugin is still required [despite it being deprecated by the JUnit team](https://github.com/junit-team/junit5/issues/1317). However, my hunch is that this is only the case if no

    test {
        useJUnitPlatform()
    }

is used. Could you please clarify (in the change log) whether the note even applies with `useJUnitPlatform()`?

**Comment by sksamuel** [comment] 2018-04-11 14:17
I didn't know about that so I will try it and see how it fares.

**Comment by sschuberth** [comment] 2018-04-11 19:54
> I didn't know about that [...]

Interesting, as you added `useJUnitPlatform()` yourself over [here](https://github.com/kotlintest/kotlintest/blame/master/build.gradle#L61). 😉

**Comment by sksamuel** [comment] 2018-04-11 20:09
Hmm so I did. I think I probably added that when I spent an entire night trying to hunt down while the tests were continuing to hang under 4.6.

**Comment by bondpp7** [comment] 2018-04-12 12:29
I tried, and found that the tests are not found if you do not include the gradle-plugin, even with `useJUnitPlatform()`.  It would be nice if this could be corrected, as including both is likely to eventually cause issues as they update JUnit.

**Comment by sschuberth** [comment] 2018-04-13 13:52
I'm observing similar issues with running unit test from the command line like `./gradlew test`:

- With only `useJUnitPlatform()` tests hang.
- With only the plugin / classpath applied the test task is always `SKIPPED`.
- Likewise with `useJUnitPlatform()` *and* the plugin / classpath applied the test task is always `SKIPPED`.

Bottom line, I cannot get kotlintest 3 to work at all.

**Comment by oripwk** [comment] 2018-04-14 09:43
I want to join @sschuberth.

The combination of Gradle 4.6 and KotlinTest 3.0.x is impossible to run correctly.

The tests _do_ run using IntelliJ, but when running `./gradlew clean test` it just doesn't work.

I tried any combination of `buildScript` section with or without `testCompile` dependencies, and `test` clause with `junitPlatform()` command. It either doesn't work, or always reports `BUILD SUCCESSFUL`

**Comment by sksamuel** [comment] 2018-04-16 00:11
But we know it does work in some scenarios because you can see in Travis the output of tests being ran.

https://travis-ci.org/kotlintest/kotlintest/jobs/366758866#L560
If you look at that log, you can see that lines 560 onwards are only generated by the ClassifyTest. So it's definitely being executed. And travis is using `./gradlew test`.

One thing that I can't get it to do is output the names of the tests that ran.

**Comment by sschuberth** [comment] 2018-04-16 19:45
> One thing that I can't get it to do is output the names of the tests that ran.

Yeah, that's indeed annoying. I've configured things like

    testLogging {
        events 'started', 'passed', 'skipped', 'failed'
        exceptionFormat 'full'
    }

but there's no output about the individual tests being run whatsoever.

**Comment by sschuberth** [comment] 2018-04-16 20:01
FYI, with `useJUnitPlatform()` and kotlintest 3.1.0-RC1, when running `./gradlew --info test` I get

    Gradle Test Executor 2 STANDARD_ERROR
        Apr 16, 2018 9:53:04 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
        WARNING: TestEngine with ID 'io.kotlintest' failed to discover tests
        java.lang.IllegalArgumentException: Class should have a single no-arg constructor: class com.here.ort.scanner.Resources
            at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:281)

So that exception seems to be the reason why no tests are discovered. Any idea why kotlintest is looking for a `com.here.ort.scanner.Resources` class?

**Comment by sksamuel** [comment] 2018-04-17 03:50
Ok good spot @sschuberth. I'll update the class scanner to work with nested internal objects.

**Comment by sksamuel** [comment] 2018-04-17 03:50
Ok good spot @sschuberth. I'll update the class scanner to work with nested internal objects.

**Comment by sschuberth** [comment] 2018-04-17 06:55
> I'll update the class scanner to work with nested internal objects.

Please note though that the object is not nested [in my case](https://github.com/heremaps/oss-review-toolkit/blob/0778552bfb14ef2409f1bebfaaaa160aacf3a9eb/scanner/src/test/kotlin/ScanCodeTest.kt#L29).

**Comment by sksamuel** [comment] 2018-04-17 09:12
Why can't you do this.javaClass.getResource

**Comment by sschuberth** [comment] 2018-04-17 09:59
Looks like this is indeed a left-over from when I had a global utility function like

    internal object Resources

    fun readResource(path: String): List<String> {
       return File(Resources.javaClass.getResource(path).toURI()).readLines()
    }

But in any case, kotlintest should not choke on a class definition like this.

**Comment by sschuberth** [comment] 2018-04-17 10:07
I've removed `internal object Resources`, and now I'm getting

    Skipping task ':scanner:test' as task onlyIf is false.

**Comment by sschuberth** [comment] 2018-04-17 10:44
I believe the only reasonable way forward is to only use `useJUnitPlatform()` instead of applying the deprecated plugin and find out why running the tests is hanging. When running Gradle with `--debug` I get

    12:38:31.180 [DEBUG] [TestEventLogger]
    12:38:31.180 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STARTED
    12:38:31.178 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$1$1
    12:38:31.183 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$1$2
    12:38:31.184 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$1
    12:38:31.184 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$2$1
    12:38:31.186 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$2$2
    12:38:31.186 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$2$3
    12:38:31.187 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1$2
    12:38:31.188 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest$1
    12:38:31.193 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanCodeTest
    12:38:31.193 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1$1
    12:38:31.194 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1$2
    12:38:31.195 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1$3
    12:38:31.196 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1$4
    12:38:31.197 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1$5
    12:38:31.197 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest$1
    12:38:31.199 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor] Executing test class com.here.ort.scanner.ScanResultsCacheTest
    12:38:31.831 [DEBUG] [TestEventLogger]
    12:38:31.831 [DEBUG] [TestEventLogger] com.here.ort.scanner.ScanCodeTest STARTED
    12:38:34.502 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34295877632, Free: 17539252224}
    12:38:34.502 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34295877632, Free: 17539252224}
    12:38:34.502 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1073741824, Committed: 536870912}
    12:38:34.810 [DEBUG] [sun.rmi.transport.tcp] RMI Scheduler(0): close connection
    12:38:34.984 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(1)-127.0.0.1: (port 28662) connection closed
    12:38:34.984 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(1)-127.0.0.1: close connection
    12:38:36.817 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
    12:38:36.818 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
    12:38:36.818 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
    12:38:36.819 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
    12:38:36.820 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
    12:38:36.820 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
    12:38:36.820 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
    12:38:39.502 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34295877632, Free: 17573167104}
    12:38:39.502 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34295877632, Free: 17573167104}
    12:38:39.502 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1073741824, Committed: 536870912}
    12:38:43.270 [DEBUG] [sun.rmi.transport.tcp] RMI Scheduler(0): close connection
    12:38:43.309 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(4)-127.0.0.1: (port 28662) connection closed
    12:38:43.309 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(4)-127.0.0.1: close connection
    12:38:44.298 [DEBUG] [sun.rmi.transport.tcp] RMI Scheduler(0): close connection
    12:38:44.326 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(6)-127.0.0.1: (port 28662) connection closed
    12:38:44.327 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(6)-127.0.0.1: close connection
    12:38:44.502 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34295877632, Free: 17580494848}
    12:38:44.503 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34295877632, Free: 17580494848}
    12:38:44.503 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1073741824, Committed: 536870912}
    12:38:46.818 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
    12:38:46.819 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
    12:38:46.819 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
    12:38:46.820 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
    12:38:46.823 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
    12:38:46.823 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
    12:38:46.824 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.

So, in contrast to using the plugin, test are discovered and in fact started. But it seems to be running into some sort of endless loop as the last part of the log keep repeating indefinitely.

**Comment by sksamuel** [comment] 2018-04-17 10:48
Do you have a task called onlyIf ?

**Comment by sschuberth** [comment] 2018-04-17 10:50
> Do you have a task called onlyIf ?

Nope. But I don't believe it refers to a task name anyway, but to a task's [onlyIf method](https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#org.gradle.api.Task:onlyIf(groovy.lang.Closure)).

**Comment by sksamuel** [comment] 2018-04-19 01:29
I've made good progress on the source of the hang. It's caused by the way junit handles notifications that tests are running. The gradle implementation is getting confused by nested tests.

**Comment by sschuberth** [comment] 2018-04-19 08:03
> The gradle implementation is getting confused by nested tests.

Thanks for looking into this! Just curious, does it make sense to file a Gradle issue about that, and have you done so already?

**Comment by sksamuel** [comment] 2018-04-20 03:44
I believe the current master has this fixed. I'll do another 3.1.0 release candidate as soon as I can so we have other people verify the fix.

**Comment by sksamuel** [comment] 2018-04-24 00:14
I'd be very grateful if people would give 3.1.0-RC2 a go. I believe you can now just use the junit support instead of the plugin.

https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md#version-31x---in-progress

**Comment by sschuberth** [comment] 2018-04-24 11:36
In my initial test 3.1.0-RC2 seems to be working fine! Even output the names of the tests that ran seems to be working. Thanks!

**Comment by bondpp7** [comment] 2018-04-27 14:16
The SpringListener doesn't seem to be working: `lateinit property controller has not been initialized`

Code under test:
```
@SpringBootTest
class TransactionDemoApplicationTests : BehaviorSpec() {
    override fun listeners() = listOf(SpringListener)

    @Autowired
    lateinit var controller: Controller

    init { .... }
}
```

Autowired depenedency:
```
@RestController
class Controller {

    @Autowired
    lateinit var entityManager: EntityManager

    .....
}
```

My setup:
kotlinVersion = '1.2.40'
springBootVersion = '1.5.12.RELEASE'
junitVersion = '5.1.1'

in build.gradle:

```
  dependencies {
    testCompile('io.kotlintest:kotlintest-runner-junit5:3.1.0-RC2')
    testCompile('io.kotlintest:kotlintest-extensions-spring:3.1.0-RC2')
  }

  test{
    useJUnitPlatform()
  }
```

**Comment by bondpp7** [comment] 2018-04-27 14:32
Also, the class name is being prepended on each output:
![image](https://user-images.githubusercontent.com/24767464/39367958-43a7eeaa-4a06-11e8-87f3-0a057593de4b.png)

**Comment by sschuberth** [comment] 2018-04-27 14:48
> Also, the class name is being prepended on each output:

About that, also see https://github.com/kotlintest/kotlintest/issues/312

**Comment by bondpp7** [comment] 2018-04-27 14:52
I'll track the naming in 312;

For the spring listener: I can help test, again, if that would be useful.

**Comment by sksamuel** [comment] 2018-05-07 21:09
3.1.0-RC3 is out now and if there are no further showstoppers I think we could be ready for 3.1.0 final.

**Comment by sksamuel** [comment] 2018-05-10 14:12
Can you check this is now fixed in 3.1.0-RC4 and we can close the ticket.

**Comment by sksamuel** [comment] 2018-05-11 12:53
3.1.0 final is now released and the gradle plugin is no longer required. Please re-open if further issues on this.

**Closed by sksamuel** 2018-05-11 12:53 UTC
Labels: question

**Comment by jpbulman** [comment] 2020-10-07 21:22
Not sure if this is just me, but the thing that _finally_ fixed this was adding
```
  testImplementation 'io.kotest:kotest-assertions-core-jvm:$version'
```
instead of 
```
 testImplementation 'io.kotest:kotest-assertions-core:<version>' 
```
(the latter is the one recommended in the quick start guide on the docs page).

**Comment by sksamuel** [comment] 2020-10-07 21:53
You shouldn't need -jvm if you're on a recent version of gradle (so they say).

**Comment by jpbulman** [comment] 2020-10-07 21:55
According to my gradle-wrapper.properties, I should be running a newer version (5.6.2)
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-bin.zip
```

**Comment by sksamuel** [comment] 2020-10-07 22:14
I think it's 6+ that will do it automatically.

**Comment by jpbulman** [comment] 2020-10-08 00:09
That might be good to add to the quick start guide, because the [way it is currently worded](https://kotest.io/quick_start/#gradle) makes it sound like this should work on 4.6+

> For Gradle 4.6 and higher...

Is the kotest docs website open source?

**Comment by sksamuel** [comment] 2020-10-08 00:25
Yes, in the docs folder in master.
