### ISSUE TITLE
Test Case Config does not behave as I expected

### ISSUE THREAD

**Issue by Jager567** [kotlintest/kotlintest#476] opened 2018-11-20 22:51 UTC
[The documentation](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#test-case-config) states that I can add a timeout to a test. It states that it is "Useful for code that is non-deterministic and **might not finish**". This leads me to believe that this setting will stop the test execution after the given duration has passed. However, when I accidentally executed a test that called a method with an infinite loop, it didn't stop the execution after the timeout had passed. Is this a documentation issue, a fault on my side or a bug?

After some testing, I found out that this fails, but only after the full test has finished:
```Kotlin
class FiniteLoopString: StringSpec() {
    "has a long finite loop test".config(timeout = 100.milliseconds) {
        val startTime = currentTimeMillis()
        while (currentTimeMillis() < startTime + 1000) {
            "this" shouldNotBe "that"
        }
    }
}
```
while the following test just keeps running forever:
```Kotlin
class InfiniteLoopString: StringSpec() {
    "has an infinite loop test".config(timeout = 100.milliseconds) {
        while (true) {
            "this" shouldNotBe "that"
        }
    }
}
```

During my testing, I also found that this test succeeds, even though it takes longer than the timeout:
```Kotlin
class SuccessfulTest: WordSpec() {
    init {
        "String.length" should {
            "return the length of the string".config(timeout = 2.seconds) {
                val startTime = currentTimeMillis()
                while (currentTimeMillis() < startTime + 10000) {
                    "this" shouldNotBe "that"
                }
            }
        }
    }
}
```

**Comment by sksamuel** [comment] 2018-11-20 22:53
Definitely a bug. The timeout should kick in for any test that takes longer than the timeout.

**Comment by sksamuel** [comment] 2018-11-20 22:54
Which version of kotlintest ?

**Comment by Jager567** [comment] 2018-11-20 22:54
I tested this with version `3.1.10`.

**Comment by Kerooker** [comment] 2018-12-30 03:53
I'll grab this if you're not working on it, @sksamuel .

**Comment by sksamuel** [comment] 2019-01-02 09:02
I'll fix this as part of #518 as it will need to work differently.

**Comment by sksamuel** [comment] 2019-01-02 10:33
Added. Review as part of #518

**Comment by sksamuel** [comment] 2019-01-09 13:36
Please try 3.2.0-RC1 as this should be fixed now. @Jager567

**Comment by Jager567** [comment] 2019-01-09 21:49
It seems that test cases now fail correctly, but they still aren't aborted when they haven't finished executing within the timeout period. This means that
```Kotlin
class SuccessfulTest: WordSpec() {
	init {
		"String.length" should {
			"return the length of the string".config(timeout = 2.seconds) {
				val startTime = currentTimeMillis()
				while (currentTimeMillis() < startTime + 10000) {
					"this" shouldNotBe "that"
				}
			}
		}
	}
}
```
now correctly fails, but only after having executed for 10 seconds, while a test with an infinite loop will never finish.

**Comment by sksamuel** [comment] 2019-01-09 22:09
A normal test should abort if it's interruptable.

The problem is how do you interrupt a while loop.
You can't.

I can inject a thread interrupt.
I can cancel a coroutine.

But if you want to use an unbounded while loop then you're on your own.

**Comment by sksamuel** [comment] 2019-01-09 23:32
Ok, if junit is doing it, then it's probably using Thread.stop, which I can do as well, but it's been deprecated since Java 1.1. That will actually "kill" a thread in the way I said was impossible. I should have said "impossible without hacky solutions" :)

I suppose we _could_ do the same in theory. Let me look into their implementation.

**Comment by sksamuel** [comment] 2019-01-09 23:33
And you're right, at the very least the docs should be clear.

**Comment by sksamuel** [comment] 2019-01-09 23:37
So JUnit's implementation is surprising to me.

They just wait xx seconds, and if you're not finished, they'll interrupt your thread, and then carry on, reporting it as failed. So your test report is all hunky dory.

Your thread won't actually be killed though, and it'll just continue in the background until the JVM shuts down. I suppose they are either naive, or assume that the JVM will terminate after the tests complete.

I'm not sure which is better.

@Kerooker thoughts?

**Comment by sksamuel** [comment] 2019-01-22 01:42
In 3.2.1 the behavior is now the same as JUnit.

**Closed by sksamuel** 2019-01-22 01:42 UTC
Labels: bug
