### ISSUE TITLE
Strange "Behavior Spec" behavior

### ISSUE THREAD

**Issue by A-Zaiats** [kotlintest/kotlintest#163] opened 2017-03-20 23:10 UTC
Hello.
I tried the last 2.0-SNAPSHOT of kotlinspec (built from [this commit](https://github.com/kotlintest/kotlintest/commit/752dddf0c3622f5b75a32035e31c30a372ae1aae)). I have next code:
```kotlin
class Test : BehaviorSpec() {
    init {

        Given("test") {

            When("when 1") {
                println("when 1")

                Then("test 1") {
                    println("test 1")
                }
                Then("test 2") {
                    println("test 2")
                }
            }

            When("when 2") {
                println("when 2")

                Then("test 3") {
                    println("test 3")
                }
                Then("test 4") {
                    println("test 4")
                }
            }
        }

    }
}
```
And there are outputs:
```

oneInstancePerTest = true     |     oneInstancePerTest = false
when 1                        |     when 1
when 2                        |     when 2
when 1                        |     test 1
when 2                        |     test 2
test 1                        |     test 3
when 1                        |     test 4
when 2 
test 2 
when 1
when 2
test 3
when 1
when 2
test 4
```

May I am wrong, but I think `when` block must be running separately just for inner `then` block:
```
when 1 -> test 1 -> test 2
when 2 -> test 3 -> test 4
```
so I can write something like that:
```
Given(a user try to login)

    When(login was failed)  // mock request, configured via Mockito, returns error, valid for this `when` block
        Then(show error for user)

    When(login is success) // the same mock request returns success, valid for this `when` block
        Then(store auth token)
        Then(redirects user to main)
```

**Comment by helmbold** [comment] 2017-03-21 19:56
I'd expect this for `oneInstancePerTest = false` :

```
when 1 -> test1
when 1 -> test2
when 2 -> test3
when 2 -> test4
```

The order could obviously be different with multiple instances, however the `when` block should be executed before each `then` block, what is not the case.

**Comment by JLLeitschuh** [comment] 2017-04-12 18:34
This does seem strange, especially if `when 2` could side effect data declared in the `init` method and you only want this side effect to occur when running `when 2` tests

**Comment by darkengine** [comment] 2017-06-15 08:17
I'm wondering the logic of multiple WHEN in one GIVEN{}. Because I wrote the following code in my demo:
`
class MyBehaviorSpec: BehaviorSpec() {
    init {
        given("a stack") {
            val stack = Stack<String>()
            println("new-stack ")
            `when`("an item is pushed") {
                println("when-push ")
                stack.push("kotlin")
                then("the stack should not be empty") {
                    println("then-check-1 ")
                    stack.isEmpty() shouldBe false
                }
            }
            `when`("the stack is popped") {
                println("when-pop ")
                stack.pop()
                then("the stack should be empty") {
                    println("then-check-2 ")
                    stack.isEmpty() shouldBe true
                }
            }
        }
    }
}
`

It came out that all WHEN got executed first, and all codes inside THEN{} after that. So the first stack-empty-check failed here. Is that we shouldn't put multi WHEN inside a GIVEN?

The output is like this:
`
new-stack 
when-push 
when-pop new-stack 
when-push 
when-pop 
then-check-1 

java.lang.AssertionError: expected: false but was: true
Expected :false 
Actual   :true
----- call stack ------

new-stack 
when-push 
when-pop 
then-check-2 
`

**Comment by jschamburger** [comment] 2017-07-26 11:40
Any news on this? With 2.0.3 we still have the same problem as described above.
I could reproduce it not only with BehaviorSpec but also with FeatureSpec. All `feature` clauses are executed before all `scenario` clauses.

**Comment by sksamuel** [comment] 2017-10-04 05:11
I think oneInstancePerTest affects things, but isn't the root cause. I'm looking into it.

**Comment by newcat** [comment] 2018-01-18 11:46
The problem might be related to this:
When I used interceptors to do setup work before the tests were run, I noticed that code in the `Given` and `When` blocks is executed **before** the spec interceptor is called.

Test setup:
```
class Test : BehaviorSpec() {
    override fun interceptSpec(context: Spec, spec: () -> Unit) {
        System.out.println("Before Spec")
        spec()
        System.out.println("After Spec")
    }

    init {
        Given("Given") {
            System.out.println("Running Given")
            When("When") {
                System.out.println("Running When")
                Then("Then 1") { System.out.println("Running Then 1") }
                Then("Then 2") { System.out.println("Running Then 2") }
            }
        }
    }
}
```

Result:
```
oneInstancePerTest = false
Running Given
Running When
Before Spec
Running Then 1
Running Then 2
After Spec
```
```
oneInstancePerTest = true
Running Given
Running When
Before Spec
Running Given
Running When
Running Then 1
Running Given
Running When
Running Then 2
After Spec
```

IMO the spec interceptor should be called before any code in a given, when or then block is executed.

**Comment by bondpp7** [comment] 2018-02-07 16:56
Any news on this? This effectively makes the behavior spec unreliable in its current form.

**Comment by kastork** [comment] 2018-03-20 17:07
There's something more fundamental at work with `interceptSpec`, I think.
For example, if you have two specs of type `FunSpec`, and each is `override val oneInstancePerTest = false`, and each one having a `override fun interceptSpec` defined.  Then  the `interceptSpec` of the first spec to execute is called, but not the second.

**Comment by sksamuel** [comment] 2018-03-21 11:14
The whole `oneInstancePerTest` thing was a mistake in my opinion. It means the underlying implementation problematic, as you have to re-create and re-run lambdas from the test scopes. I note that Spek doesn't offer this feature, probably because it's more hassle than it's worth.

**Comment by sksamuel** [comment] 2018-03-24 02:12
This is fixed in 3.0.0 RC1.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md

**Closed by sksamuel** 2018-03-24 02:12 UTC
Labels: bug

**Comment by kastork** [comment] 2018-03-25 23:47
The RC build(s) don't appear to be in Jcenter or maven central.  Do you have a snapshot repo?

I also tried building/installing locally, but it seems the  project doesn't have the usual `publishToMavenLocal` task.

**Comment by sksamuel** [comment] 2018-03-26 05:56
There was an issue with maven central so RC1 went missing but RC2 is there
now.
