### ISSUE TITLE
BehaviorSpec does not allow for configuration

### ISSUE THREAD

**Issue by JLLeitschuh** [kotlintest/kotlintest#142] opened 2017-02-02 19:37 UTC
It seems like there is no good way to configure the individual `BehaviorSpec` tests.

**Comment by helmbold** [comment] 2017-02-02 20:16
Do you mean the `config` method is missing? It seems like you are right then! We haven't implemented it yet.

**Comment by helmbold** [comment] 2017-02-02 21:02
Maybe we could use [typesafe builders](http://kotlinlang.org/docs/reference/type-safe-builders.html) to improve BehaviorSpec and add `config`.

**Comment by JLLeitschuh** [comment] 2017-02-05 03:05
Shouldn't it be on the `then`?

**Comment by helmbold** [comment] 2017-02-05 06:13
You're right, since config can contain many test cases.

**Comment by helmbold** [comment] 2017-02-05 20:14
I've transformed the code to a type-safe builder and made `config` available on `then` (via exposing the TestCase). However the "given" and "when" texts and hierarchy levels are not shown in the test runner view.
![behaviorspec](https://cloud.githubusercontent.com/assets/5079980/22629521/e58d3e9c-ebe7-11e6-9fa0-60211b771954.png)
@sksamuel do you have an idea what could be wrong?

**Comment by sksamuel** [comment] 2017-02-05 20:46
Can't seem to spot why. But you do invoke `check()` as well as pass it to the test case.

**Comment by helmbold** [comment] 2017-02-05 21:29
Thanks, the call of `check()` is indeed redundant, but not the cause of the problem. I've added some println statements to BehaviorSpecParenthesisTest: 

```
class BehaviorSpecParenthesisTest : BehaviorSpec() {
  init {
    given("a sheet of string cells 4x4") {
      println("given")
      `when`("get existing cell by reference (like A1 or B2)") {
        println("when")
        then("should contain its value") {
          println("then")
          // noop
        }
      }
    }
  }
}
```

... and the output is: 
```
given
when
given
when
then
```

So there must be something completely wrong. But I have no idea what.

**Comment by helmbold** [comment] 2017-02-19 14:09
I've just tried how a behavior spec test is displayed in IntelliJ without my changes and it looks like this:
![behaviorspec](https://cloud.githubusercontent.com/assets/5079980/23103020/2e1460c4-f6b4-11e6-91c0-8423e75d3cdc.png)

I think that something is fundamentally wrong with behavior spec, but I have no idea (yet) how to fix it.

I've added some `println` statements to the existing code, but it prints only "then":

```kotlin
    Given("a sheet of string cells 4x4") {
      println("given")
      When("get existing cell by reference (like A1 or B2)") {
        println("when")
        Then("should contain its value") {
          println("then")
          // noop
        }
      }
    }
```

**Comment by sksamuel** [comment] 2017-02-19 14:16
I'll try and fix it this week if you promise not to rename everything
aftetwards :)


On 19 Feb 2017 14:09, "Christian Helmbold" <notifications@github.com> wrote:

I've just tried how a behavior spec test is displayed in IntelliJ without
my changes and it looks like this:
[image: behaviorspec]
<https://cloud.githubusercontent.com/assets/5079980/23103020/2e1460c4-f6b4-11e6-91c0-8423e75d3cdc.png>

I think that something is fundamentally wrong with behavior spec, but I
have no idea (yet) how to fix it.

I've added some println statements to the existing code, but it prints only
"then":

    Given("a sheet of string cells 4x4") {
      println("given")
      When("get existing cell by reference (like A1 or B2)") {
        println("when")
        Then("should contain its value") {
          println("then")
          // noop
        }
      }
    }

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kotlintest/kotlintest/issues/142#issuecomment-280921412>,
or mute the thread

**Comment by helmbold** [comment] 2017-02-19 14:20
... I'll do my best :-) 

I've just tried it on my branch and *today*, only "then" is printed, too. Maybe there is a problem in the interaction KotlinTest/IntelliJ/JUnit.

**Comment by sksamuel** [comment] 2017-03-14 00:08
Ok I've fixed this and I'm going to merge it in.

**Comment by sksamuel** [comment] 2017-03-14 00:09
@helmbold Merge this PR if you're happy https://github.com/kotlintest/kotlintest/pull/160

**Comment by helmbold** [comment] 2017-03-16 19:45
Merged.

**Closed by helmbold** 2017-03-16 19:45 UTC
Labels: bug
