### ISSUE TITLE
ProjectConfig should be auto-scanned, not in the specific package

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#470] opened 2018-11-12 15:17 UTC
Currently, the `ProjectConfig` class **must be** placed at `io.kotlintest.provided`, or else it won't be discovered and won't work as per [the documentation](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#project-config).

However, this is not very good for users. I want to create my ProjectConfig anywhere (for example, my own package `me.kerooker.test.configs`), and KotlinTest should work with it.

**Comment by Kerooker** [comment] 2018-11-12 15:21
I see that there's a note:

```
Note: This is a breaking change from versions 2.0 and before, in which KotlinTest would scan the classpath for instances of this class. It no longer does that, in favour of the predefined package name + classname.
```

And I **strongly** disagree with it. The predefined package name + classname is very bad for usage, and my team currently doesn't want to use `ProjectConfig` because of the necessity to use a "dirty" package that is not ours and make the project uglier

**Comment by sksamuel** [comment] 2018-11-12 17:17
Your two options are:

1. Scan the classpath for instances of an interface `ProjectConfig`
2. Use Class.forName to instantiate an instance of a well known class.

We went with the former initially in versions 1 and 2 and as @helmbold will attest, all it did was cause bug report after bug report. Plus it takes ages on large classpaths - minutes - adding in this delay to every test run.

Yes it's a tiny bit ugly to have one package different from your others but if anyone has an alternative to options 1 and 2 I'd like to hear it.

**Comment by sksamuel** [comment] 2018-11-12 21:36
Using Reflections library.
Where's the annotation going to go. On a class that we know of the name of :)

**Comment by Kerooker** [comment] 2018-11-12 22:09
No, I mean that we can create a compile-time annotation and process at compile time which classes are annotated (instead of before each test). And when we find this classes, we save them in a xml (for example) so that we know them at runtime (using a ServiceLoader), for example.

I'll try to fiddle with this a little bit and see if I can get an example

**Comment by sksamuel** [comment] 2018-11-13 12:29
It seems complicated and error prone.

What about a system property to allow you to override the location if you want to. So your team can set the location of `ProjectConfig` to `com.wibble.Whatever`

**Comment by lwasyl** [comment] 2019-08-19 10:35
Since the issue is already here, I'll try to argue for reopening it to search for better alternative than right now.

In our case the issue is that we have multiple modules, and would like to have both project-wide (to set isolation mode) and module-wide (to add e.g. Android-related watchers) configurations. Right now the only reasonable solution is to subclass `AbstractProjectConfig` in the common module and then subclass it again in each module, some of which will maybe also provide some own configuration.

The thing is it doesn't compose well. For example with Gradle's new `testFixtures` functionality it'd be nice to be able to contribute watchers to set and clean up some state relevant to specific module for example. 

Perhaps it'd make sense to allow providing listeners, filters and extensions, while still requiring single point of truth for execution order, timeout etc.?

**Comment by sksamuel** [comment] 2019-08-24 11:27
How would you envisage it working to achieve multiple configs?

**Comment by lwasyl** [comment] 2019-08-24 14:58
I have couple of thoughts: 

 1. Perhaps the Reflections library had some inefficiences that have since been removed? Since as I understand speed was core argument for moving towards current solution
 1. Maybe loading subclasses would be efficient by limiting the search to just single package e.g. `io.kotlintest.provided`? In this case users would still have to put configuration in single package, but would be allowed to have multiple classes there and all would be used by KT.
 1. Another solution would be to use Java's ServiceLoader mechanism. With [AutoService](https://github.com/google/auto/tree/master/service) it would effectively mean previously suggested annotation processor, but without burden of maintaining it. Loading such services is simple, and AutoService would of course be optional, as it's still very straightforward to add manifest entries manually.

I don't expect 1. to be the case, but maybe. 2. would be acceptable if searching in given package had constant complexity, which may or may not be the case. 3. would be the least _hacky_ solution, but relatively complex for the users. Not so much for it to be a dealbreaker IMO (on the contrary, I think it'd be a great feature)

Of course all of those would assume core configuration is allowed only in one place, and only listeners/extensions can be injected

**Comment by sksamuel** [comment] 2019-08-24 18:02
So you can have a project config per module not just per project. Or do you
want multiple project configs inside one module ?

As for your solutions. Reflections was slow yes. But we've since replaced
reflections with classgraph which faster. So we could go back to classpath
scanning in theory.

We would need a solution for JS as 4.0 of KotlinTest will be MPP enabled.

**Comment by lwasyl** [comment] 2019-08-24 19:01
> So you can have a project config per module not just per project. Or do you
want multiple project configs inside one module ?

Both. But it shouldn't matter anyway, since anything allowing for multiple configs would work in both cases I think.

> We would need a solution for JS as 4.0 of KotlinTest will be MPP enabled.

I'm not familiar with JS so I don't even know what's possible here :\ Would it mean it should also work in Kotlin/Native context?

**Comment by sksamuel** [comment] 2019-08-24 19:07
I can think of a JS solution.

How would multiple configs per package work? Would you just see them all
merged together basically?

**Comment by lwasyl** [comment] 2019-08-24 20:41
Yes, I imagine all the listeners and extensions from all configurations found on classpath (so both for module and those brought by dependencies) are merged. Order of execution for listeners/extensions from multiple configurations would be unspecified.

One thing that imo should be specified is the behavior where more than one instance of the same listener is found on the classpath. In such case I'd opt for printing a warning and executing all of them anyway. Although in the one non-merged configuration class (as there'd still have to be one for parallelism etc.) it could be further configurable, if needed

**Comment by sksamuel** [comment] 2019-08-24 20:57
So playing devils advocate I'm still unsure why the current situation
doesn't work for you. If you want multiple configs merged you could just
make one  big config. Is it because you just don't want a big file?

**Comment by lwasyl** [comment] 2019-08-24 21:18
I don't want a big file, but more importantly I don't want to repeat that file (and all the listeners) in every module. 

In my specific case I'd simply prefer to add dependency on `textFixtures(project(":A"))` and `textFixtures(project(":B"))` and have listeners from both enabled automatically. `A` contains listeners for RxJava's error handling, `B` to set up Android Architecture Components threading executors. I hoped to be able to easily add dependency on yet another module which would automatically install convenient console logger for our custom logging solution etc. Since quite a lot of modules depend on all three, in different configurations, that would simplify things.

As a side note, [the same feature in JUnit5](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic) is considered _advanced_ and off by default.

**Comment by sksamuel** [comment] 2019-08-25 00:24
I think we can do service loading as well as config. Doesn't seem advanced
to me. It's not like you'd end up doing it by accident.

**Comment by sksamuel** [comment] 2019-11-25 04:21
Re-opening this ticket, and targeting 4.0 to re-enable classpath scanning. We should also support more than one file, and merging them.

Let's make sure we avoid this issue again.
https://github.com/kotlintest/kotlintest/issues/219

**Comment by sksamuel** [comment] 2020-01-13 07:36
With https://github.com/kotlintest/kotlintest/commit/56afd7f057a14e837c7576bcb0c98db649c0f07c the project config is now using classpath scanning. There is no project config merging because there are settings that do no stack. The first detected config will win out (we could warn / error if mutliple?)

But with #1143 we will also start scanning for project wide listeners and extensions, so they do not need to be explicitly added to anything. This will better address the feature request of multiple config files.

**Closed by sksamuel** 2020-01-13 07:36 UTC
Labels: enhancement, framework
