### ISSUE TITLE
Support for @Before and @After in AnnotationSpec

### ISSUE THREAD

**Issue by dave08** [kotlintest/kotlintest#513] opened 2018-12-26 16:34 UTC
This could be very useful for those migrating from JUnit without tests that are too complicated.

**Comment by Kerooker** [comment] 2018-12-26 16:35
Makes sense.
However, should `@Before` be executed before Test or before Spec?

**Comment by dave08** [comment] 2018-12-26 16:37
I think it should conform to JUnit, the point is to make for easy migration and compatibility.

**Comment by Kerooker** [comment] 2018-12-26 16:38
I'm not sure how JUnit works in this sense. I believe there's a @BeforeClass and a @Before. The first would run before Spec while the later would be run after Test, I suppose

**Comment by dave08** [comment] 2018-12-26 16:39
https://www.baeldung.com/junit-before-beforeclass-beforeeach-beforeall, I think they sum things up pretty well.

**Comment by Kerooker** [comment] 2018-12-26 16:42
I think we should jump straight to `@BeforeEach` and `@BeforeAll`, that are from JUnit5, and ignore JUnit4. What do you think? Should we support both?

**Comment by dave08** [comment] 2018-12-26 16:44
I think both, since those with JUnit4 tests can just derive from AnnotationSpec, and don't have to change anything else... maybe those old annotations can be marked as deprecated if you want people to follow one convention on new tests...

**Comment by Kerooker** [comment] 2018-12-26 16:47
People would have to change imports anyway.

Marking as deprecated is introducing an old testing model (JUnit4) into a new testing framework (KT).

If we're going to help people, I believe only JUnit5 should be supported. IF we keep giving support to somewhat legacy or old code, codebases will never change

**Comment by Kerooker** [comment] 2018-12-26 16:48
They're ambiguous in JUnit4, and they'll be ambiguous in Kotlintest if we do that.

Do you think it's very necessary?

**Comment by dave08** [comment] 2018-12-26 16:55
For those with lots of tests... even junit took the time to make Junit Vintage so that they don't just drop all those users that don't have the time to upgrade... importing new annotations is just an alt-enter here and there...

By the way, do you really need your own Test (etc...) annotation? Maybe you could use JUnit's wouldn't that make things a bit simpler (and less confusing, imagine a user accidentally imports the JUnit version, how would they now why their tests are not being discovered?). Unless it would mean an extra dependency...

**Comment by Kerooker** [comment] 2018-12-26 17:00
Maybe we could start accepting both Junit's @Test and our @Test, in case of accidents.

We don't want the necessity of users to add the JUnit dependencies to use KotlinTest, and we should provide our own annotations.

And maybe you're correct, we should create a TypeAlias for both @Before and @After, but deprecate them.

**Comment by dave08** [comment] 2018-12-26 17:03
Is there currently any way to add such a before to an AnnotationSpec without declaring a whole listener? I just need to reset mocks before each test and I need the references to those objects...

**Comment by Kerooker** [comment] 2018-12-26 17:12
There is.

```

class Foo : AnnotationSpec() {

@Test
fun foo() {
"BAR" shouldBe "BAR
}

override fun beforeTest(description: Description) {
    // clear mocks
  }

override fun afterTest(description: Description, result: TestResult) {
 // Do after
}
}

```

You can also abuse the test isolation with `isInstancePerTest() = true`, so that your class is instantiated everytime

**Comment by dave08** [comment] 2018-12-26 17:15
Also `@Ignore` could be very useful.

**Comment by Kerooker** [comment] 2018-12-26 17:16
You're correct on that one too.
I'll see what can be done

**Comment by Kerooker** [comment] 2018-12-26 17:17
@sksamuel 
I think all these points are pretty valid for AnnotationSpec. But I also do believe that maybe we could add them to other specs if users would rather use them instead of overriding the `beforeTest` function and functions alike

**Comment by Kerooker** [comment] 2018-12-26 17:18
For instance

```
class Foo : FreeSpec() {

@Before
fun before() {
// Do my before
}

init {
   "Foo" - {
       "Should bar" {
             "bar" shouldBe "bar"
        }
   }
}
}
```

Could prove to be a valid syntax

**Comment by dave08** [comment] 2018-12-26 17:20
In other tests, it would probably be better to integrate them into the DSL somehow for consistency... Since personally I don't like the init block unless I have to use it.. also it's not too clear when code running in an outside scope actually runs? In Spek it's a mess and you need to do beforeXXX { } for everything because the grouping scopes get run at discovery time, is this the same in KotlinTest?

**Comment by Kerooker** [comment] 2018-12-26 17:31
That's correct. It's not possible by design, as it only executes `block()` inside init.

We encourage the usage of `init`, as it makes the DSL pretty clear and easy to use. Personally, I never use the constructor directly. I prefer to have them all in a class, and use it that way in my company's code

**Comment by Kerooker** [comment] 2018-12-26 17:32
If we do it the way you made your example, the code will become cumbersome the same way as Spek, and we want to avoid it.

Functions in the class outside of the `init` block is the way we find best right now.

**Comment by dave08** [comment] 2018-12-26 17:37
Doesn't it all get executed at test run anyways, unlike Spek? Spek does it in two stages, which makes things unclear and hard to reason about, but the constructor is the equivalent of the init block without possibility for overrides, but with a proper DSL things could be great.

With Spek, I couldn't count on code in the `"Foo" - { }` above to be run before all the tests under it... if with KotlinTest it does, that avoids alot of the mess. The only thing is the beforeTest and that might be a different one per test group in the same class... which makes `@Before` less interesting.

**Comment by Kerooker** [comment] 2018-12-26 17:44
Ok, so let me clarify it a little bit

```
class Foo : FreeSpec() {
   
override fun beforeTest(description: Description) = println("BEFORE")

    init {
        "Foo" - {
            println("FOO")
            "BAR" - {
                println("BAR")
                "BAZ" {
                     println("BAZ")
                }
            }
        }
    }   
}

```

should print

```
BEFORE
FOO
BAR
BAZ
```

**Comment by dave08** [comment] 2018-12-26 17:54
That's great, exactly what one would expect, but when there are two tests, then 
```kotlin
class Foo : FreeSpec() {
   
override fun beforeTest(description: Description) = println("BEFORE")

    init {
        "Foo" - {
            println("FOO")
            "BAR" - {
                println("BAR")
                "BAZ" {
                     println("BAZ")
                }
               "BAZ2" {
                     println("BAZ2")
                }
            }
            "BAR2" - {
                println("BAR2")
                "BAZ" {
                     println("BAZ")
                }
               "BAZ2" {
                     println("BAZ2")
                }
            }
        }
    }   
}
```
it will be
```
BEFORE
FOO

BAR
BAZ
BEFORE
BAZ2

BAR2
BAZ
BEFORE
BAZ2
```
What if we want:
```
FOO
BAR
BEFORE
BAZ
BEFORE
BAZ2

BAR2
BEFORE
BAZ
BEFORE
BAZ2
```
?

**Comment by dave08** [comment] 2018-12-26 18:09
Actually, I just ran that previous example and it gave me this:
```
BEFOREFOO
BEFOREBAR
BEFORE
BAZ
BEFORE
BAZ2
BEFOREBAR2
BEFORE
BAZ
BEFORE
BAZ2```
Which is VERY funny... why is it running even before the groupings?

**Comment by Kerooker** [comment] 2018-12-26 18:09
It executes exactly as you want. Your test class will actually execute like this:

```
    [Foo, bar, before, baz]
    [foo, bar, before, baz2]
    [foo, before, bar]
    [foo, bar2, before, baz]
    [foo bar2, before, baz2]
    [foo, before, bar2]
    [before, foo]
```

**Comment by dave08** [comment] 2018-12-26 18:11
Which fuzzies the whole definition of beforeTest and the user's mental model of it, no? I don't think this behavior is even documented?

**Comment by Kerooker** [comment] 2018-12-26 18:37
I believe it's just the form that the engine operates, and I don't believe there's a problem.

@sksamuel can validate this

**Comment by Kerooker** [comment] 2018-12-26 19:55
@dave08 
I added an initial WIP implementation.
Some things to consider: KT doesn't even include JUnit in it's classpath, so we won't be accepting JUnit's Annotations for now.

I decided to leave out legacy `@Before`, `@After`, `@BeforeClass` `@AfterClass` for now, until we further discuss it if we do.

**Comment by Kerooker** [comment] 2018-12-27 12:43
We could, but I'm not really sure if we should. If the user wants to use everything from JUnit so much, I don't believe there's any need to use KotlinTest in that case. If it's really necessary to do it, just go ahead and use JUnit + KotlinTest Assertions

**Comment by dave08** [comment] 2018-12-27 12:46
The use case is what I mentioned before (like in my case): easy migration from JUnit. New tests will probably be using one of the DSLs, the old ones don't have to be changed too much. I've personally have had lots of `empty suite` and similar errors from using more than one test runner on Android. I currently have to run each test one by one (until I finish the migration and just remove the other frameworks).

**Comment by Kerooker** [comment] 2018-12-27 12:48
Didn't expect that to be a problem. I use JUnit + KT in many classes here, but I didn't believe Android would be a problem for that

Ok, you convinced me. I'll reflect JUnit's annotations

**Comment by Kerooker** [comment] 2018-12-27 12:51
Although....
Wouldn't it be better to create our own annotations, and if you want you can change the import?

**Comment by Kerooker** [comment] 2018-12-27 12:53
This way we would just add in the legacy annotations, and you could change them all when you're changing to AnnotationSpec (you would have to do something in the class anyways)

**Comment by dave08** [comment] 2018-12-27 13:16
I think that all those extra annotations should only be a support layer. If it wasn't too much work, it might even a good idea to use a Strategy Pattern here, or have a completely seperate JUnitSpec type for this. Your own annotations should only be the ones that are recommended in my opinion.

**Comment by dave08** [comment] 2018-12-27 13:32
But once they finish the migration, all they need is to remove the setting, and they'll be changing to supported annotations as they go along. The setting is just to remove the extra overhead of reflection. If a user migrating has to do too much, they probably won't do it... and to support this as an option in the library is much easier than changing hundreds of imports manually.

**Comment by sksamuel** [comment] 2018-12-27 14:49
It's been a busy christmas so I'm just catching up on this thread and there's been quite a discussion!

Some points.

1. Allowing people to switch a test class from junit4 or 5 to kotlintest is great so we should support all annotations - ignore before beforeclass and so on.

We can do this by simply shadowing the annotation package names then we don't need to add junit to the classpath. We already do this for the @TestFactory. This means zero changes for the user other than extending the spec.

2. These annotations should not be used outside of AnnotationSpec as there's no need. If you're writing a new test in a KT style then use a listener or override method.

3. In terms of which closures are excuted in which order - at the moment it works but is a little clunky. In 3.2 there is a new isolation mode setting which gives you finer control.

**Comment by dave08** [comment] 2018-12-27 14:58
On point 2 @sksamuel, I'm just wondering why not support before/afterXXX inside the DSL, it would give more fine-grained control on these inside the tests themselves, and also make it more clear and give the possibility to use the `val`s initialized inside the DSL instead of forcing everything to be at the class level.

**Comment by Kerooker** [comment] 2018-12-27 15:12
I disagree. 
Adding these functions inside the test scope will make much more clutter, and it won't be simple. Ok, 1% of the userbase will have a more fine-grained control, but the other 99% will be very confused with it

**Comment by sksamuel** [comment] 2018-12-27 15:33
Do you think it would be that bad? It's an optional syntax form. Would be
top level only. I do want to be careful we don't make something as ugly as
Spek though.

**Comment by Kerooker** [comment] 2018-12-27 15:35
The behavior in Spek is confusing because for every test you have to add a `beforeTest` and an `afterTest`.... I'm afraid that this becames way too cluttered and confusing for new users. Moving from a JUnit syntax to KotlinTest is already a big step. Having to learn how all these scopes work may be too much and make users give up.

I'm not completely against it tho. However, we must give a lot of thought into it before moving anything in that direction

**Comment by sksamuel** [comment] 2018-12-27 18:55
something like

```kotlin
Class myTest : StringSpek({ 

  before {

  }
 
  "test 1" {

  }


  "test 2" {


  }
})
```

why not allow it inside init too.

**Comment by dave08** [comment] 2018-12-27 21:31
Before isn't good in this context, since unlike Spek, just put the code there without before. You really mean beforeEach or beforeEachTest which does something very different, in Spek you need it for the first kind too since the code runs during the test discovery stage before any test runs unless you use before, which is one reason why spek is messier, also memoized in spek is necessary for the same reason, whereas in kotlintest a val can be declared straight in the dsl without an extra lambda around it and it'll be run only when the tests run... much cleaner! The addition of a few beforeXXXs don't clutter when they're used for their real purpose.

**Comment by sksamuel** [comment] 2018-12-27 22:37
Actually beforeEach isn't needed if you use the correct isolation mode - where a new Spec class is created for every test.

Then you can just use val's as before and they're re-created every time.

**Comment by Kerooker** [comment] 2018-12-30 02:42
@dave08  and @sksamuel 
I believe the PR is ready for a revision

**Comment by sksamuel** [comment] 2019-01-02 19:41
I'm adding this to the 3.2 milestone. No reason why we can't sneak this in.

**Comment by Kerooker** [comment] 2019-01-02 19:58
I guess it's ok. It will be good if we can deliver 3.2 soon tho

**Comment by sksamuel** [comment] 2019-01-02 20:12
I think we're only a day or two away from RC1.

**Closed** 2019-01-03 15:01 UTC
Labels: enhancement
