### ISSUE TITLE
Consider reducing the number of specs

### ISSUE THREAD

**Issue by superbobry** [kotlintest/kotlintest#66] opened 2016-07-07 16:35 UTC
This may look like a weird request, and it probably is, but have you considered reducing the number of *Spec classes? This will allow the library to be more opinionated in how the tests should be written, which is good IMO. 

For instance, `StringSpec` and `FunSpec` are almost the same, modulo an extra `test` call. I think using `String.invoke` to define tests is a clever hack, but wrapping the string in `test` is just an concise and much less surprising for the user. 

Similar reasoning applies to `ShouldSpec`. Are the cases defined with `should` any different from the ones defined with `test`? Maybe. But is it worth the extra concept in the library? 

What do you think?

**Comment by russel** [comment] 2016-07-07 17:07
A priori a good idea I think. I suspect ScalaTest ended up with so many variants in an attempt to please all the people all the time, especially with the TDD/BDD (artificial) schism. Yes having support for end-to-end and BDD testing is a good thing. Property-based and example-based testing (unit or otherwise) is a good thing. The question is which is the best way of expressing these in the language in an idiomatic way. Then the question arises should Spek (and KSpec) and KotlinTest see themselves as complements or competition. Both are viable but affect the thinking on what to do.

**Comment by sksamuel** [comment] 2016-07-07 17:08
I'm open minded to what people want, but my personal opinion is that does it really matter? I write Scala code every day at work, and I only ever use WordSpec but doesn't matter to me there's 10 other specs.

**Comment by russel** [comment] 2016-07-07 17:21
It's just an issue of: a) providing newcomers with positive guidance for writing appropriate tests; and b) avoiding maintenance effort that is not available. 

In Scala I think I only use FunSuite and ProSpec. Mostly I have no idea what the others would do for me. It doesn't matter there are others as long as someone else maintains any that are used.

**Comment by helmbold** [comment] 2016-07-07 17:26
I had the same feeling about the number of styles, but then they are miserly a matter of taste. I don't like the style Spek offers and it is the reason I don't use this framework. Personally I prefer String spec and could live without should spec and fun spec, but @superbubory prefer these styles...

**Comment by superbobry** [comment] 2016-07-07 17:35
@helmbold Just to clarify, I am just starting with kotlintest after JUnit, so I don't have a preference at the moment. My main point was nicely summarized by @russel in the comment above.

**Comment by sksamuel** [comment] 2016-07-07 17:52
So as it appears, with even a small sample in this thread, that we all like different styles. That's showing right there the reason they should remain.

I think what we can do though is adopt one as our "introduction" style and promote that. And relegate the others further down the readme. Which one would you guys recommend as "the" one.

**Comment by lenguyenthanh** [comment] 2016-07-07 18:05
I prefer String speak, the most elegant one.

**Comment by helmbold** [comment] 2016-07-07 18:25
I prefer String Spec, too. It was me who introduced ShouldSpec, but you do the same with an even more reduced syntax and a bit more flexibility (sometimes "should" is not optimal an you would go start with another word like "it" for example.

**Comment by sksamuel** [comment] 2016-07-07 18:26
I use StringSpec. Sounds like StringSpec is popular.

**Comment by russel** [comment] 2016-07-07 18:36
In a sense StringSpec is FunSpec without the fun, sorry test.

I am currently switching FunSpec to StringSpec.

I would also like to remove the init {…} but that cannot happen yet.

**Comment by sksamuel** [comment] 2016-07-07 18:37
If you too want rid of init {} please consider adding your voice to this https://discuss.kotlinlang.org/t/init-block-for-constructor-body/1703/8

**Comment by russel** [comment] 2016-07-07 18:44
@sksamuel I have voiced an opinion.

**Comment by superbobry** [comment] 2016-07-07 19:53
I am not opposed to StringSpec as well, although in general I'd follow the principle of least surprise when it comes to APIs.

**Comment by superbobry** [comment] 2016-07-08 09:46
One more point: having a single (or at least less varying) syntax for defining tests makes IDE support (for running a single test) easier.

**Comment by reckter** [comment] 2016-07-08 17:30
Why not create one Spec, that pleases all the want for the different styles? Is there an exclusion between String spec and WordSpec? I can't see a reason why both shouldn't be possible ( same with the other Specs)

**Comment by sksamuel** [comment] 2016-07-08 18:00
There could be one spec to rule them all. Again it's just down to the fact the project was created as a clone of ScalaTest and that's how it does it. We can always change it. I think now the project is gaining real popularity, and lots of feedback, we're getting some good ideas, and for 2.0 everything can be up for discussion.

**Comment by helmbold** [comment] 2016-07-08 20:59
@reckter Merging all styles into one wouldn't  improve anything. We would have as many ways to write tests as today and probably more because styles could be mixed. And the code could become somewhat messy.

**Comment by russel** [comment] 2016-07-09 08:21
@superbobry  Having strings as function names is fairly standard in Groovy, so I do not think that a problem.

@sksamuel  @reckter Having a consistent style in a given test class seems like a very good idea to me. Enforcing it with the inheritance is a nice mechanism as Scala has shown. If there is a desire to have multiple styles then the status quo works fine. The addition of StringSpec has made the FunSpec more or less redundant I suspect.

**Comment by sksamuel** [comment] 2016-07-11 04:54
So two good points raised here. Having the specs separated means a single test class has to all use the same format and if we did merge them you'd be able to mix them in ways that were unintended.

**Comment by helmbold** [comment] 2016-07-11 21:19
It seems like this discussion have been come to a standstill. There are good reasons to keep existing specs and there are good reasons to keep the related classes separated. So, there are basically two options:

* close this issue
* decide what specs should be removed (I think FunSpec, FlatSpec, and ShouldSpec could be replaced by StringSpec).

**Comment by hastebrot** [comment] 2016-07-12 04:27
>I think FunSpec, FlatSpec, and ShouldSpec could be replaced by StringSpec

@helmbold Hmm, `FunSpec` in ScalaTest was actually created for teams coming from Ruby's RSpec tool (http://www.scalatest.org/at_a_glance/FunSpec). `StringSpec` is missing things like `describe()` and `it()`.

`WordSpec`, `ShouldSpec`, `FlatSpec` and `FreeSpec` look very similar and one could possibly just use `StringSpec`.

**Comment by sksamuel** [comment] 2016-07-12 05:25
Personally, since there's no real agreement it just sounds like we should keep it like it is.

**Comment by helmbold** [comment] 2016-07-12 08:38
I tend to leave it as is, too. I think it would be fine to use StringSpec for all examples and still offer the other styles. If we learn that some specs are rarely used, we could deprecate them later.

**Comment by superbobry** [comment] 2016-07-12 10:04
> If we learn that some specs are rarely used, we could deprecate them later.

Deprecating features early is be easier and safer than later on in the life of the project.

**Comment by sksamuel** [comment] 2016-07-12 22:22
@superbobry agreed, early deprecation is best. I think in this case though we don't know if we even want to deprecate yet. Some people are saying have one spec, others (like me) are saying leave it alone as it works and everyone seems to like a different spec.

For me, @helmbold's last comment is the best approach.

**Comment by helmbold** [comment] 2016-07-17 18:57
We should remove FlatSpec in 2.0. It requires an irregular syntax for `config` and adds nothing compared to StringSpec:

```kotlin
// FlatSpec
"String.length" should "return the length of the string" {
  ...
}

// StringSpec
"String.length should return the length of the string" {
  ...
}
```

Removing FlatSpec would make #78 unnecessary. And, caused by redundancy, there is a bug #79, what would be "fixed" by removing, too.

Are there any objections?

**Comment by sksamuel** [comment] 2016-07-17 19:00
It's fine, remove it.

**Comment by sksamuel** [comment] 2016-07-19 14:26
One thing it does add that I forgot about earlier is that when you use the same name on the left (before the should) it will nest it in the output for you. That's quite nice, and StringSpec won't do that.

**Comment by helmbold** [comment] 2016-07-19 18:39
Do you want to reintroduce FlatSpec then?

**Comment by sksamuel** [comment] 2016-07-19 18:44
Well I don't know. Your point that the config doesn't work is valid.

**Comment by helmbold** [comment] 2016-07-19 18:53
I'd say that we should only reintroduce it, if we could make the `config` syntax regular (and obviously fix the bug).

**Comment by helmbold** [comment] 2016-09-08 19:32
Can we close this issue? I think there it wouldn't result in anything to leave it open.

**Closed** 2016-09-08 20:02 UTC
Labels: question
