### ISSUE TITLE
Should throw should allow for assignments to throw exceptions

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#387] opened 2018-07-27 13:01 UTC
I expect this syntax to be possible, as the assignment throws an exception:

```
class Playground : FreeSpec() {
    
    class Foo {
        var bar = "bar"
        set(value) {
            throw Exception()
        }
    }
    
    init {
        "Should throw" {
            val foo = Foo()
            
            shouldThrow<Exception> { 
                foo.bar = "baz"
            }
        }
    }
}
```

**Comment by sksamuel** [comment] 2018-07-27 17:12
Ok so the issue is that an assignment is not an expression, and the shouldThrow excepts a function that returns a value.

We can change the shouldThrow definition to say the function returns a unit, but then you get warnings if your function does return a value.

I'm not sure if it's possible to get both to work, if not, I would have to add another function like shouldThrowUnit for use cases above. What do you think ?

**Comment by Kerooker** [comment] 2018-07-27 17:31
A workaround, current is to do something like
```
shouldThrow<Exception> {
foo.bar = "baz"
""   //This will be returned
}
```

**Comment by Kerooker** [comment] 2018-07-27 17:35
The only problem in my branch right now is that you can't have both the functions in the same class. We'll have to put them in another namespace, as they're considered the same in this class, but it might work

**Comment by sksamuel** [comment] 2018-07-27 17:37
The function would have to be called shouldThrowUnit { } so that it has a different name. Not elegant but would work.

**Comment by Kerooker** [comment] 2018-07-27 17:37
It's not a problem to have the same name, they just must be in different namespaces

**Comment by sksamuel** [comment] 2018-07-27 17:40
Is that more confusing or less? If you tried to use both in the same file, one would just not compile, and you'd have to know to manually add another import ?

**Comment by Kerooker** [comment] 2018-07-27 17:40
And one can be an overload of the other. For example, I created the workaround in my application:

```
inline fun <reified T: Throwable> shouldThrow(thick: () -> Unit) : T {
        return io.kotlintest.shouldThrow(thick)
    }
```

This can be in kotlintest too, but must be in different packages. I'm not usre if it's less elegant than `shouldThrowUnit`

**Comment by Kerooker** [comment] 2018-07-27 17:40
That may be more confusing, indeed

**Comment by sksamuel** [comment] 2018-07-27 17:41
Both are not ideal, perhaps there's a trick one can do that one of the Jetbrains team knows about @udalov

**Comment by sksamuel** [comment] 2018-08-09 23:13
In the end I've added `shouldThrowUnit` until this anomaly is fixed by Jetbrains.

**Closed by sksamuel** 2018-08-09 23:13 UTC
Labels: bug
